# Generated by Django 5.0.6 on 2024-07-08 18:19

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ArchivedUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('middle_name', models.CharField(blank=True, max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('mother_maiden_name', models.CharField(max_length=50)),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=6)),
                ('date_of_birth', models.DateField()),
                ('address', models.CharField(max_length=100)),
                ('lga', models.CharField(max_length=50)),
                ('state', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('phone_number', models.CharField(max_length=20)),
                ('nin', models.CharField(max_length=20)),
                ('passport_photograph', models.ImageField(upload_to='archived_passport_photos/')),
                ('certificate_number', models.CharField(max_length=20)),
                ('application_type', models.CharField(choices=[('New', 'New'), ('Renewal', 'Renewal'), ('Reissue', 'Reissue')], max_length=10)),
                ('status', models.CharField(choices=[('Active', 'Active'), ('Expired', 'Expired')], max_length=20)),
                ('center_location', models.CharField(max_length=100)),
                ('application_id', models.CharField(max_length=100, unique=True)),
                ('license_number', models.CharField(max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='NewApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('middle_name', models.CharField(blank=True, max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('mother_maiden_name', models.CharField(max_length=50)),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=6)),
                ('date_of_birth', models.DateField()),
                ('address', models.CharField(max_length=100)),
                ('lga', models.CharField(max_length=50)),
                ('state', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone_number', models.CharField(max_length=20)),
                ('nin', models.CharField(max_length=20, unique=True)),
                ('passport_photograph', models.ImageField(upload_to='passport_photos/')),
                ('certificate_number', models.CharField(max_length=20)),
                ('application_type', models.CharField(choices=[('New', 'New'), ('Renewal', 'Renewal'), ('Reissue', 'Reissue')], max_length=10)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Processing', 'Processing'), ('Approved', 'Approved'), ('Ready for Printing', 'Ready for Printing')], default='Pending', max_length=20)),
                ('center_location', models.CharField(max_length=100)),
                ('application_id', models.CharField(blank=True, default=uuid.uuid4, max_length=100, null=True, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='LicenseRenewal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('license_number', models.CharField(max_length=20, unique=True)),
                ('license_expiration_date', models.DateField()),
                ('applicant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dlApplication.newapplication')),
            ],
        ),
        migrations.CreateModel(
            name='LicenseReissue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('license_number', models.CharField(max_length=20)),
                ('license_expiration_date', models.DateField()),
                ('reissue_reason', models.TextField()),
                ('reissue_date', models.DateField(auto_now_add=True)),
                ('affidavit_or_police_report', models.FileField(upload_to='reissue_documents/')),
                ('applicant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dlApplication.newapplication')),
            ],
        ),
    ]
