# Generated by Django 5.0.6 on 2024-07-06 07:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dlApplication', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='licensereissue',
            name='new_license_expiration_date',
        ),
        migrations.RemoveField(
            model_name='licensereissue',
            name='new_license_number',
        ),
        migrations.RemoveField(
            model_name='licenserenewal',
            name='medical_certificate',
        ),
        migrations.RemoveField(
            model_name='licenserenewal',
            name='renewal_fee',
        ),
        migrations.RemoveField(
            model_name='licenserenewal',
            name='vision_test_result',
        ),
    ]
