# Generated by Django 5.0.6 on 2024-07-07 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DriverLicense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('holder_name', models.CharField(max_length=200)),
                ('license_number', models.CharField(max_length=100, unique=True)),
                ('issue_date', models.DateField()),
                ('expiration_date', models.DateField()),
                ('status', models.CharField(choices=[('Valid', 'Valid'), ('Suspended', 'Suspended'), ('Fake', 'Fake'), ('Expired', 'Expired')], default='Valid', max_length=50)),
            ],
        ),
    ]
