# Generated by Django 5.0.6 on 2024-07-08 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DriverLicense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100)),
                ('license_number', models.CharField(max_length=20, unique=True)),
                ('issued_date', models.DateField()),
                ('expiry_date', models.DateField()),
                ('status', models.CharField(choices=[('valid', 'Valid'), ('suspended', 'Suspended'), ('expired', 'Expired'), ('fake', 'Fake')], max_length=20)),
            ],
        ),
    ]
