# Generated by Django 5.0.6 on 2024-07-08 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('licenseValidation', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driverlicense',
            name='status',
            field=models.CharField(choices=[('Valid', 'Valid'), ('Fake', 'Fake'), ('Expired', 'Expired')], default='Valid', max_length=50),
        ),
    ]
